--- 
abstract: Turn the front LED on Apple laptops on and off via ADB
author: Ævar Arnfjörð Bjarmason <avar@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Linux-Apple-Laptop-LED
no_index: 
  directory: 
    - inc
    - t
requires: 
  Exporter: 0
tests: t/*.t
